### ISSUE TITLE
感觉你这个是不是可以吧那些命令接口都释放出来

### ISSUE THREAD

**Issue by berry0511** [DAN-AND-DNA/NanoRedisClient#2]
想set、get的那些，都封装成函数了，但是对外我看了还是用的raw去手动输入命令啊

**Comment by DAN-AND-DNA** [comment]
@berry0511 你好，可以根据raw去封装新的set和get函数，因为raw是走线程池，可以不阻塞游戏线程的，而旧的set都是阻塞模式的

**Comment by 2332370844** [comment]
你好，你这个插件可以向redis中写入吗

**Comment by 2332370844** [comment]
如果可以，我应该调用哪个节点呐

**Comment by berry0511** [comment]
> 如果可以，我应该调用哪个节点呐

可以，set或者hset就可以写啊

**Comment by 2332370844** [comment]
我没有找到你说的这个，你可以给我发张调用的图片吗

**Comment by berry0511** [comment]
> 我没有找到你说的这个，你可以给我发张调用的图片吗
需要自己通过RAW来写命令
也可以用pipeline吧，那个我没试过
![image](https://github.com/DAN-AND-DNA/NanoRedisClient/assets/16091368/653ad7ab-63ad-4b2a-9cea-fb4005a397d8)

**Comment by berry0511** [comment]
![image](https://github.com/DAN-AND-DNA/NanoRedisClient/assets/16091368/bd86fb88-3c7f-4bef-8333-0b7d9b9256f7)
需要自己通过raw去写，这个比较方便了
或者通过pipeline啥的


> 我没有找到你说的这个，你可以给我发张调用的图片吗
